name: App test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
        name: Check out repository code

      - name: Set up Python 3.x
        uses: actions/setup-python
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python mbpstester.py
          python mbpstester.py --log
          python mbpstester.py --log --network-info
          python mbpstester.py --no-download
          python mbpstester.py --no-upload
          python mbpstester.py --network-info
          python mbpstester.py --json test_output.json
